Repository MLH-Fellowship/project-flask-flamingos, pull requests merged in 2022-09, with the labels that each got.

#10 added profiles.json to put all our information making it easy to refe…
  .vscode/settings.json
  app/__init__.py
  app/static/img/carson-profile-image.jpg
  app/static/profiles.json
  app/static/styles/main.css
  app/templates/index.html
  development.env
Labels: enhancement

#16 Added my information to the profiles json
  app/static/profiles.json
Labels: enhancement

#12 added routes and html templates
  app/__init__.py
  app/templates/education.html
  app/templates/experience.html
  app/templates/hobbies.html
  app/templates/index.html
  app/templates/places.html
Labels: enhancement

#17 added field to signify if the job is a present job or not for styling…
  app/static/profiles.json
Labels: enhancement

#21 Edit Profiles.json -- Added Alia description
  app/static/img/alia-profile-image.jpg
  app/static/profiles.json
Labels: enhancement

#22 Adding Sebastian's information into the json file.
  app/static/img/sebastian-profile-img.png
  app/static/profiles.json
Labels: enhancement

#30 Education & Work-experiences templates + Some Refactoring Jinga templates
  app/__init__.py
  app/static/profiles.json
  app/static/styles/main.css
  app/templates/education.html
  app/templates/headShots.html
  app/templates/hobbies.html
  app/templates/index.html
  app/templates/menuBar.html
  app/templates/work-experience.html
Labels: enhancement

#31 added menuBar Jinja template
  app/templates/experience.html
  app/templates/index.html
  app/templates/menuBar.html
Labels: bug

#35 added MIT license
  LICENSE
Labels: documentation
